# Generated by Django 6.0.4 on 2026-04-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_course_tag_mission_course_discussion_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background halaman materi.', null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='mission',
            name='image',
            field=models.ImageField(blank=True, help_text='Gambar tambahan untuk materi.', null=True, upload_to='missions/'),
        ),
        migrations.AddField(
            model_name='mission',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link video YouTube untuk materi ini.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
