# Generated by Django 6.0.4 on 2026-04-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_mission_background_image_mission_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='gamification_mode',
            field=models.CharField(blank=True, choices=[('level1', 'Level 1: Tebak Vektor/Bitmap'), ('level2', 'Level 2: Hitung Anchor Point'), ('level3', 'Level 3: Palet & Warna'), ('level4', 'Level 4: Rakit Maskot'), ('level5', 'Level 5: Drag & Drop File')], help_text='Pilih mode evaluasi gamifikasi jika ada.', max_length=20, null=True),
        ),
    ]
