# Generated by Django 6.0.4 on 2026-05-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_mission_gamification_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Isi konten atau kuis sederhana yang muncul setelah token dimasukkan.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload modul PDF untuk misi ini.', null=True, upload_to='modul/'),
        ),
    ]
