# Generated by Django 6.0.4 on 2026-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_communityroom_mission_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityroom',
            name='description',
        ),
        migrations.RemoveField(
            model_name='communityroom',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='mission',
            name='module_file',
            field=models.FileField(blank=True, null=True, upload_to='modules/'),
        ),
        migrations.AlterField(
            model_name='communityroom',
            name='content',
            field=models.TextField(default='Pertanyaan contoh atau kuis sederhana'),
        ),
        migrations.AlterField(
            model_name='communityroom',
            name='token',
            field=models.CharField(help_text='Token to access the room', max_length=20, unique=True),
        ),
    ]
