# Generated by Django 6.0.4 on 2026-05-06 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_communityroom_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityroom',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='communityroom',
            name='content_mode',
            field=models.CharField(choices=[('material', 'Materi'), ('quiz', 'Kuis'), ('both', 'Materi + Kuis')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='communityroom',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='communityroom',
            name='store_scores',
            field=models.BooleanField(default=False, help_text='If enabled, quiz submissions will be stored for this room'),
        ),
        migrations.AlterField(
            model_name='communityroom',
            name='content',
            field=models.TextField(default='Selamat datang di ruang kelas ini.'),
        ),
        migrations.CreateModel(
            name='CommunityMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='community_materials/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='dashboard.communityroom')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CommunityQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
                ('explanation', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='dashboard.communityroom')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CommunityQuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to='dashboard.communityroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='CommunityRoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dashboard.communityroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-joined_at',),
                'unique_together': {('room', 'user')},
            },
        ),
        # NOTE: `UniqueStreak` table was created manually earlier (script).
        # The CreateModel operation for UniqueStreak has been removed to
        # avoid conflict with the existing table. If the table schema
        # differs, recreate migrations appropriately.
    ]
