# Generated by Django 6.0.4 on 2026-05-13 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_communityroom_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        # The UniqueStreak table already exists in the database (created manually),
        # so we skip creating it here to avoid conflicts. If the table schema
        # differs from the model, adjust migrations or the DB accordingly.
    ]
